name: Lint and Test Charts

on:
  pull_request:
    branches: [main]
    paths:
      - 'charts/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list)
        id: list
        run: |
          changed=$(ct list --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list.outputs.changed == 'true'
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        if: steps.list.outputs.changed == 'true'
        uses: helm/kind-action@v1.9.0

      - name: Run chart-testing (install)
        if: steps.list.outputs.changed == 'true'
        run: ct install --config ct.yaml

      - name: Install helm-unittest plugin
        if: steps.list.outputs.changed == 'true'
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Run helm unit tests
        if: steps.list.outputs.changed == 'true'
        run: |
          for chart in charts/*/; do
            if [ -d "$chart/tests" ]; then
              echo "Running unit tests for $chart"
              helm unittest "$chart"
            fi
          done
