name: Version Check and Auto Tag

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'

permissions:
  contents: write

jobs:
  check-version-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for chart changes
        id: check-changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^charts/"; then
            echo "charts-changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "charts-changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Check version changes and create tags
        if: steps.check-changes.outputs.charts-changed == 'true'
        run: |
          new_tags=""
          for chart_dir in charts/*/; do
            if [ ! -d "$chart_dir" ]; then continue; fi
            
            chart_name=$(basename "$chart_dir")
            chart_file="$chart_dir/Chart.yaml"
            
            if [ ! -f "$chart_file" ]; then continue; fi
            
            # Get current version
            current_version=$(grep '^version:' "$chart_file" | awk '{print $2}' | tr -d '"'"'"'"')
            
            # Check if tag exists
            tag_name="$chart_name-v$current_version"
            if ! git tag -l | grep -q "^$tag_name$"; then
              echo "Creating new tag: $tag_name"
              git tag "$tag_name"
              new_tags="$new_tags$tag_name "
            fi
          done
          
          if [ -n "$new_tags" ]; then
            echo "Pushing tags: $new_tags"
            git push origin --tags
            echo "Tags pushed successfully. The release workflow will be triggered automatically."
          else
            echo "No new tags to create."
          fi
